/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InputFileDisplay.java
 *
 * Created on May 14, 2010, 4:37:23 AM
 */

package Visual;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Danich
 */
public class InputFileDisplay extends javax.swing.JFrame {
    private CGame Game;
    /** Creates new form InputFileDisplay */
    public InputFileDisplay(CGame _Game) {
        Game = _Game;
        initComponents();
        setBounds(0, 0, getWidth()+100, Toolkit.getDefaultToolkit().getScreenSize().height);
        setVisible(true);

    }
    public void AppendToDisplay(String s)
    {
        jTextArea1.append(s);
        jTextArea1.setCaretPosition(0);
    }
    public void PrintToDisplay(String s)
    {
        jTextArea1.setText(s);
        jTextArea1.setCaretPosition(0);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jShowByTurnsMenuItem = new javax.swing.JMenuItem();
        jShowTurnNMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jShowAllRobotsActivityMenuItem = new javax.swing.JMenuItem();
        jShowRobotNActivityMenuItem = new javax.swing.JMenuItem();
        jShowRobotNActivityInTurnNMenuItem = new javax.swing.JMenuItem();
        jShowAllRobotsCodeMenuItem = new javax.swing.JMenuItem();
        jShowRobotsNCodeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu2.setText("Turns");

        jShowByTurnsMenuItem.setText("Show by Turns");
        jShowByTurnsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowByTurnsMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(jShowByTurnsMenuItem);

        jShowTurnNMenuItem.setText("Show Turn #");
        jShowTurnNMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowTurnNMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(jShowTurnNMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Robots");

        jShowAllRobotsActivityMenuItem.setText("Show All Robots' Activity");
        jShowAllRobotsActivityMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowAllRobotsActivityMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(jShowAllRobotsActivityMenuItem);

        jShowRobotNActivityMenuItem.setText("Show Robot's # Activity");
        jShowRobotNActivityMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowRobotNActivityMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(jShowRobotNActivityMenuItem);

        jShowRobotNActivityInTurnNMenuItem.setText("Show Robot's # Activity in Turn #");
        jShowRobotNActivityInTurnNMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowRobotNActivityInTurnNMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(jShowRobotNActivityInTurnNMenuItem);

        jShowAllRobotsCodeMenuItem.setText("Show All Robots' Code");
        jShowAllRobotsCodeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowAllRobotsCodeMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(jShowAllRobotsCodeMenuItem);

        jShowRobotsNCodeMenuItem.setText("Show Robot's # Code");
        jShowRobotsNCodeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowRobotsNCodeMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(jShowRobotsNCodeMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jShowAllRobotsActivityMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowAllRobotsActivityMenuItemActionPerformed
        PrintToDisplay(Game.DisplayByRobots(null));
    }//GEN-LAST:event_jShowAllRobotsActivityMenuItemActionPerformed

    private void jShowByTurnsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowByTurnsMenuItemActionPerformed
        PrintToDisplay(Game.DisplayByTurns(null));
    }//GEN-LAST:event_jShowByTurnsMenuItemActionPerformed

    private void jShowTurnNMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowTurnNMenuItemActionPerformed
        int turn;
        do
        {
            turn = Integer.valueOf(JOptionPane.showInputDialog("Type in turn number "+1+" - "+Game.getTurnCount(),"1"));
        } while ((turn < 1)||(turn > Game.getTurnCount()));
        PrintToDisplay(Game.DisplayForThisTurnAllRobots(turn, null));
        
    }//GEN-LAST:event_jShowTurnNMenuItemActionPerformed

    private void jShowAllRobotsCodeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowAllRobotsCodeMenuItemActionPerformed
        PrintToDisplay(Game.DisplayCodeOfAllRobots(null));
    }//GEN-LAST:event_jShowAllRobotsCodeMenuItemActionPerformed

    private void jShowRobotsNCodeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowRobotsNCodeMenuItemActionPerformed
        int RobotNumber;
        do
        {
            RobotNumber = Integer.valueOf(JOptionPane.showInputDialog("Type in Robot number "+0+" - "+Game.getRobotCount(),"0"));
        } while ((RobotNumber < 0)||(RobotNumber > Game.getRobotCount()));
        PrintToDisplay(Game.DisplayRobotsCode(RobotNumber, null));
    }//GEN-LAST:event_jShowRobotsNCodeMenuItemActionPerformed

    private void jShowRobotNActivityMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowRobotNActivityMenuItemActionPerformed
        int RobotNumber;
        do
        {
            RobotNumber = Integer.valueOf(JOptionPane.showInputDialog("Type in Robot number "+0+" - "+Game.getRobotCount(),"0"));
        } while ((RobotNumber < 0)||(RobotNumber > Game.getRobotCount()));
        PrintToDisplay(Game.DisplayForThisRobotTurnsAroundCurrent(RobotNumber,0, null));

    }//GEN-LAST:event_jShowRobotNActivityMenuItemActionPerformed

    private void jShowRobotNActivityInTurnNMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowRobotNActivityInTurnNMenuItemActionPerformed
        int RobotNumber;
        do
        {
            RobotNumber = Integer.valueOf(JOptionPane.showInputDialog("Type in Robot number "+0+" - "+Game.getRobotCount(),"0"));
        } while ((RobotNumber < 0)||(RobotNumber > Game.getRobotCount()));
        int TurnNumber;
        do
        {
            TurnNumber = Integer.valueOf(JOptionPane.showInputDialog("Type in Turn number "+1+" - "+Game.getTurnCount(),"1"));
        } while ((TurnNumber < 1)||(TurnNumber > Game.getTurnCount()));
        PrintToDisplay(Game.DisplayForThisRobotTurnsAroundGiven(RobotNumber,TurnNumber,1, null));

    }//GEN-LAST:event_jShowRobotNActivityInTurnNMenuItemActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jShowAllRobotsActivityMenuItem;
    private javax.swing.JMenuItem jShowAllRobotsCodeMenuItem;
    private javax.swing.JMenuItem jShowByTurnsMenuItem;
    private javax.swing.JMenuItem jShowRobotNActivityInTurnNMenuItem;
    private javax.swing.JMenuItem jShowRobotNActivityMenuItem;
    private javax.swing.JMenuItem jShowRobotsNCodeMenuItem;
    private javax.swing.JMenuItem jShowTurnNMenuItem;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
